# Generated by Django 3.1.3 on 2021-04-10 15:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('card_number', models.IntegerField(unique=True)),
                ('franchise', models.CharField(max_length=40)),
                ('due_date', models.DateField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2021, 4, 10, 15, 38, 56, 89158))),
            ],
        ),
    ]
