# Generated by Django 3.1.3 on 2021-04-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210410_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
