# Generated by Django 3.1.3 on 2021-04-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20210410_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='due_date',
            field=models.CharField(max_length=10),
        ),
    ]
