# Generated by Django 3.1.3 on 2021-04-10 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_card', to='payments.creditcard')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to='payments.user')),
            ],
        ),
    ]
