# Generated by Django 3.1.3 on 2021-04-11 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_repayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttoken',
            name='user_credit_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.usercreditcard'),
        ),
    ]
