# Generated by Django 3.1.3 on 2021-04-10 21:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20210410_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('value_after_iva', models.BigIntegerField()),
                ('value_total', models.BigIntegerField()),
                ('iva', models.BigIntegerField()),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('PENDING', 'PENDING'), ('REVERSED', 'REVERSED')], default='PENDING', max_length=25)),
                ('payment_token', models.CharField(max_length=40)),
                ('dues', models.IntegerField()),
                ('payment_reference', models.CharField(max_length=40)),
                ('webhook_url', models.URLField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.user')),
            ],
        ),
    ]
